const {chromium,expect}=require('@playwright/test');
const {fork}=require('node:child_process');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
 const child=fork('dist/server.cjs',[],{env:{...process.env,NODE_ENV:'production',PORT:'47835',HOST:'127.0.0.1',SIFT_DATA_DIR:path.resolve('.test-data')},stdio:['ignore','ignore','pipe','ipc']});
 let browser, page;
 try {
  await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('server timeout')),20000);child.on('message',m=>{if(m.type==='sift-ready'){clearTimeout(t);resolve();}});child.on('error',reject);});
  browser=await chromium.launch({channel:'chrome',headless:true});
  page=await browser.newPage({viewport:{width:1280,height:900},locale:'tr-TR'});
  page.setDefaultTimeout(15000);
  const errors=[];let sentPayload=null;page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/ai/providers-status',route=>route.fulfill({json:{success:true,providers:{gemini:{configured:false,source:'none'},openai:{configured:false,source:'none'},anthropic:{configured:false,source:'none'},ollama:{configured:false,source:'none'}}}}));
  await page.route('**/api/ai/test-connection',route=>route.fulfill({json:{success:true,message:'Google Gemini bağlantısı başarılı!'}}));
  await page.route('**/api/ai/save-config',route=>route.fulfill({json:{success:true,message:'GEMINI ayarları kaydedildi.'}}));
  await page.route('**/api/smtp/send',async route=>{sentPayload=route.request().postDataJSON();await route.fulfill({json:{success:true,messageId:'fixture-message'}})});
  await page.route('**/api/emails/sync',async route=>{
   const body=route.request().postDataJSON();
   const make=(type,id)=>({id,uid:1,accountId:body.accountId,folder:type==='inbox'?'INBOX':type,folderType:type,from:'Fixture Sender',fromName:'Fixture Sender',fromEmail:'sender@example.com',subject:'Fixture '+type,bodyText:'Vielen Dank für Ihre Nachricht. '+ 'Full content '.repeat(50),bodyHtml:'<p>Vielen Dank für Ihre Nachricht.</p><script>parent.hacked=true</script>',snippet:'Vielen Dank für Ihre Nachricht.',date:'2026-09-18T12:00:00Z',isRead:false});
   const inbox=Array.from({length:12},(_,index)=>({...make('inbox',`in-${index+1}`),uid:index+1,subject:`Fixture inbox ${String(index+1).padStart(2,'0')}`,date:new Date(Date.UTC(2026,8,18,12,index)).toISOString()}));
   await route.fulfill({json:{success:true,messages:body.offset?[]:[...inbox,make('sent','sent'),make('spam','spam')],mailboxes:[{path:'INBOX',type:'inbox',name:'INBOX',totalMessages:12},{path:'sent',type:'sent',name:'Sent',totalMessages:1},{path:'spam',type:'spam',name:'Spam',totalMessages:1}],account:{email:body.email,provider:'gmail'}}});
  });
  await page.goto('http://127.0.0.1:47835');
  await page.locator('input[type=email]').fill('fixture@gmail.com');
  await page.locator('input[type=password]').fill('abcdefghijklmnop');
  await page.getByRole('button',{name:'Oturum Aç ve Mailleri Senkronize Et'}).click();
  const inboxCard=()=>page.getByRole('button',{name:/Fixture Sender.*Fixture inbox 12/});
  await expect(inboxCard()).toBeVisible();
  await expect(page.getByText('Fixture sent',{exact:true})).toHaveCount(0);
  await page.getByLabel('Sayfa başına mail').selectOption('10');
  await expect(page.getByText('Fixture inbox 02',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Sonraki Sayfa'}).click();
  await expect(page.getByRole('button',{name:/Fixture inbox 02/})).toBeVisible();
  await page.getByRole('button',{name:'Önceki Sayfa'}).click();
  await expect(inboxCard()).toBeVisible();
  await page.locator('aside nav button').nth(2).click();
  await expect(page.getByRole('button',{name:/Fixture sent/})).toBeVisible();
  await expect(page.getByText('Fixture inbox',{exact:true})).toHaveCount(0);
  await page.locator('aside nav button').nth(3).click();
  await expect(page.getByRole('button',{name:/Fixture spam/})).toBeVisible();
  await expect(page.getByText(/Fixture inbox/)).toHaveCount(0);
  fs.mkdirSync('test-results',{recursive:true});
  await page.screenshot({path:'test-results/mailbox.png'});
  await page.getByRole('button',{name:/Fixture spam/}).click();
  await expect(page.frameLocator('iframe[title="E-posta içeriği"]').getByText('Vielen Dank für Ihre Nachricht.')).toBeVisible();
  if(await page.evaluate(()=>Boolean(window.hacked)))throw new Error('Email script escaped sandbox');
  await page.screenshot({path:'test-results/message.png'});
  await page.keyboard.press('Escape');
  await expect(page.frameLocator('iframe[title="E-posta içeriği"]').getByText('Vielen Dank für Ihre Nachricht.')).toHaveCount(0);
  await page.getByRole('button',{name:'Oluştur',exact:true}).click();
  await page.getByPlaceholder('ad@example.com').fill('receiver@example.com');
  await page.getByTestId('compose-modal').getByPlaceholder('Konu',{exact:true}).fill('Ekli test iletisi');
  await page.getByTestId('compose-modal').getByPlaceholder('İleti',{exact:true}).fill('Merhaba, bu bir test iletisidir.');
  await page.getByRole('button',{name:'Cc / Bcc'}).click();
  await expect(page.getByText('Bcc',{exact:true})).toBeVisible();
  await page.getByTitle('E-posta ekle').click();
  await page.getByTestId('compose-modal').getByRole('button',{name:/Fixture spam/}).click();
  await expect(page.getByText(/Fixture spam.eml/)).toBeVisible();
  await page.getByRole('button',{name:'Gönder',exact:true}).click();
  await expect(page.getByTestId('compose-modal')).toHaveCount(0);
  if(!sentPayload?.mail?.attachments?.[0]?.content||sentPayload.mail.attachments[0].contentType!=='message/rfc822')throw new Error('Attached email was not sent as .eml');
  await page.getByRole('button',{name:'Etiket oluştur'}).click();
  await page.getByPlaceholder('Etiket adı').fill('Önemli');
  await page.keyboard.press('Enter');
  await expect(page.getByText('Önemli',{exact:true})).toBeVisible();
  await page.getByTitle('Ayarlar',{exact:true}).click();
  await expect(page.getByTestId('settings-page')).toBeVisible();
  await page.getByRole('button',{name:'Arayüz',exact:true}).click();
  await expect(page.getByText('Ekrandaki mail sayısı',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Yapay Zekâ',exact:true}).click();
  await page.getByPlaceholder('API anahtarı').fill('fixture-api-key');
  await page.getByRole('button',{name:'Bağlantıyı test et'}).click();
  await expect(page.getByText('Google Gemini bağlantısı başarılı!')).toBeVisible();
  await page.getByRole('button',{name:/Bağla ve güvenli kaydet/}).click();
  await page.getByRole('button',{name:'Genel',exact:true}).click();
  await page.getByRole('button',{name:'EN',exact:true}).click();
  await expect(page.getByRole('button',{name:'Interface',exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await page.screenshot({path:'test-results/settings.png'});
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('UI PASS: folder isolation, true pagination, page-size control, MIME sandbox, Escape, compose attachments, AI connection gate, labels, settings and language.');
 } catch(error) { if(page) { console.error((await page.locator('body').innerText()).slice(0,5000)); fs.mkdirSync('test-results',{recursive:true}); await page.screenshot({path:'test-results/failure.png'}); } throw error; }
 finally {if(browser)await browser.close();child.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
