import React, { useEffect, useState } from 'react';
import { Send, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { ConnectedAccount } from '../types';
import { DynamicSyncCredentials } from '../services/mailSyncService';
import { detectMailProvider } from '../services/mailProviderManager';
import { safeFetchJson } from '../services/apiClient';
import { AppTheme } from '../stores/useSettingsStore';

interface Props { isOpen:boolean; onClose:()=>void; accounts:ConnectedAccount[]; contacts:string[]; credentials:Record<string,DynamicSyncCredentials>; theme:AppTheme; onSent:(data:{to:string;subject:string;body:string;accountId:string})=>void; }
export const ComposeModal:React.FC<Props>=({isOpen,onClose,accounts,contacts,credentials,theme,onSent})=>{
  const {t}=useTranslation(); const [accountId,setAccountId]=useState(''); const [to,setTo]=useState(''); const [subject,setSubject]=useState(''); const [body,setBody]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{if(isOpen&&!accountId)setAccountId(accounts[0]?.id||'');const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[isOpen,onClose,accounts,accountId]);
  if(!isOpen)return null; const dark=theme!=='light';
  const send=async()=>{const account=accounts.find(a=>a.id===accountId);const cred=credentials[accountId];if(!account||(!cred?.password&&!cred?.accessToken)){setError(t('compose.loginRequired'));return}if(!to.trim()||!subject.trim()||!body.trim()){setError(t('compose.required'));return}setBusy(true);setError('');try{const provider=detectMailProvider(account.email);await safeFetchJson('/api/smtp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:{host:account.imapConfig?.smtpHost||provider.smtpHost,port:account.imapConfig?.smtpPort||provider.smtpPort,secure:(account.imapConfig?.smtpPort||provider.smtpPort)===465,auth:{user:account.email,...(cred.accessToken?{accessToken:cred.accessToken}:{pass:cred.password})}},mail:{to,subject,text:body}})});onSent({to,subject,body,accountId});setTo('');setSubject('');setBody('');onClose()}catch(e:any){setError(e.message||t('compose.error'))}finally{setBusy(false)}};
  return <div className="fixed inset-0 z-50 bg-black/65 grid place-items-center p-4"><div className={`w-full max-w-2xl rounded-2xl shadow-2xl ${dark?'bg-zinc-900 text-zinc-100':'bg-[#f4f1eb] text-stone-900'}`}><header className="flex items-center justify-between p-5 border-b border-zinc-500/20"><h2 className="font-bold">{t('compose.title')}</h2><button onClick={onClose}><X/></button></header><div className="p-5 space-y-3"><select aria-label={t('compose.from')} value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select><input list="sift-contacts" value={to} onChange={e=>setTo(e.target.value)} placeholder={t('compose.to')}/><datalist id="sift-contacts">{contacts.map(x=><option key={x} value={x}/>)}</datalist><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder={t('compose.subject')}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={t('compose.body')} rows={12}/>{error&&<p role="alert" className="text-sm text-rose-500">{error}</p>}<div className="flex justify-end"><button disabled={busy} onClick={send} className="btn-primary flex items-center gap-2"><Send size={16}/>{busy?t('compose.sending'):t('compose.send')}</button></div></div></div></div>;
};
