import React, { useEffect, useState } from 'react';
import { Bot, CircleHelp, Info, Languages, Palette, Shield, SlidersHorizontal, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { AIProvider, AppLanguage, AppTheme, useSettingsStore } from '../stores/useSettingsStore';
import { safeFetchJson } from '../services/apiClient';

interface SettingsModalProps { isOpen:boolean; onClose:()=>void; onOpenVaultModal?:()=>void; onOpenDesktopModal?:()=>void; onOpenLoginModal?:()=>void; }
type Tab='general'|'interface'|'ai'|'help'|'about';

export const SettingsModal:React.FC<SettingsModalProps>=({isOpen,onClose,onOpenVaultModal,onOpenDesktopModal})=>{
  const {t,i18n}=useTranslation(); const s=useSettingsStore(); const [tab,setTab]=useState<Tab>('general');
  const [apiKey,setApiKey]=useState(''); const [model,setModel]=useState(''); const [status,setStatus]=useState('');
  useEffect(()=>{if(!isOpen)return;const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[isOpen,onClose]);
  if(!isOpen)return null;
  const dark=s.theme!=='light';
  const tabs:[Tab,React.ReactNode][]=[['general',<SlidersHorizontal/>],['interface',<Palette/>],['ai',<Bot/>],['help',<CircleHelp/>],['about',<Info/>]];
  const language=(lang:AppLanguage)=>{s.setLanguage(lang);void i18n.changeLanguage(lang)};
  const image=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>s.setAppearance({backgroundImage:String(reader.result||'')});reader.readAsDataURL(file)};
  const saveAI=async(testOnly=false)=>{setStatus(t('settings.ai.saving'));try{const endpoint=testOnly?'/api/ai/test-connection':'/api/ai/save-config';const data=await safeFetchJson<any>(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:s.aiProvider,apiKey:apiKey||undefined,model:model||undefined,endpoint:s.aiProvider==='ollama'?s.ollamaEndpoint:undefined,enabled:true,isDefault:true})});setStatus(data.message||t('settings.ai.success'));if(!testOnly)setApiKey('')}catch(e:any){setStatus(e.message||t('settings.ai.error'))}};
  return <div className={`fixed inset-0 z-50 ${dark?'bg-zinc-950 text-zinc-100':'bg-[#e9e4da] text-stone-900'}`} data-testid="settings-page">
    <header className="h-16 flex items-center justify-between px-6 border-b border-black/10 dark:border-white/10"><div><h1 className="text-xl font-bold">{t('settings.title')}</h1><p className="text-xs opacity-55">Sift Mail 0.6.0</p></div><button onClick={onClose} aria-label={t('actions.close')} className="p-2 rounded-xl hover:bg-zinc-500/10"><X/></button></header>
    <div className="flex h-[calc(100vh-4rem)]"><nav className="w-60 p-4 border-r border-black/10 dark:border-white/10 space-y-1">{tabs.map(([id,icon])=><button key={id} onClick={()=>setTab(id)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm ${tab===id?'bg-emerald-600 text-white':'hover:bg-zinc-500/10'}`}>{React.cloneElement(icon as React.ReactElement<any>,{size:17})}{t(`settings.tabs.${id}`)}</button>)}</nav>
      <main className="flex-1 overflow-y-auto p-8"><div className="max-w-3xl mx-auto space-y-6">
        {tab==='general'&&<><Section title={t('settings.general.language')} icon={<Languages/>}><div className="flex gap-2">{(['tr','de','en'] as AppLanguage[]).map(l=><button key={l} onClick={()=>language(l)} className={`px-4 py-2 rounded-xl text-sm ${s.language===l?'bg-emerald-600 text-white':'bg-zinc-500/10'}`}>{l.toUpperCase()}</button>)}</div></Section><Section title={t('settings.general.security')} icon={<Shield/>}><Toggle label={t('settings.general.trackers')} checked={s.blockTrackers} onChange={s.setBlockTrackers}/><div className="flex gap-2 mt-3">{onOpenVaultModal&&<button onClick={onOpenVaultModal} className="btn">{t('settings.general.vault')}</button>}{onOpenDesktopModal&&<button onClick={onOpenDesktopModal} className="btn">{t('settings.general.desktop')}</button>}</div></Section></>}
        {tab==='interface'&&<><Section title={t('settings.interface.theme')} icon={<Palette/>}><div className="grid grid-cols-2 sm:grid-cols-5 gap-2">{(['light','dark','oled','ocean','forest'] as AppTheme[]).map(x=><button key={x} onClick={()=>s.setTheme(x)} className={`p-3 rounded-xl text-sm ${s.theme===x?'ring-2 ring-emerald-500 bg-emerald-500/10':'bg-zinc-500/10'}`}>{t(`settings.interface.themes.${x}`)}</button>)}</div></Section><Section title={t('settings.interface.customize')} icon={<Palette/>}><div className="grid sm:grid-cols-2 gap-4"><Field label={t('settings.interface.accent')}><input type="color" value={s.accentColor} onChange={e=>s.setAppearance({accentColor:e.target.value})}/></Field><Field label={t('settings.interface.font')}><select value={s.fontFamily} onChange={e=>s.setAppearance({fontFamily:e.target.value})}><option value="Inter, ui-sans-serif, system-ui, sans-serif">Inter/System</option><option value="Arial, sans-serif">Arial</option><option value="Georgia, serif">Georgia</option><option value="'Segoe UI', sans-serif">Segoe UI</option></select></Field><Field label={t('settings.interface.fontSize')}><input type="range" min="12" max="18" value={s.fontSize} onChange={e=>s.setAppearance({fontSize:Number(e.target.value)})}/></Field><Field label={t('settings.interface.pageSize')}><select value={s.pageSize} onChange={e=>s.setAppearance({pageSize:Number(e.target.value) as 10|20|50|100})}>{[10,20,50,100].map(n=><option key={n}>{n}</option>)}</select></Field><Field label={t('settings.interface.background')}><input type="file" accept="image/*" onChange={e=>image(e.target.files?.[0])}/>{s.backgroundImage&&<button onClick={()=>s.setAppearance({backgroundImage:''})} className="text-xs text-rose-500 ml-2">{t('actions.trash')}</button>}</Field></div></Section></>}
        {tab==='ai'&&<Section title={t('settings.ai.title')} icon={<Bot/>}><p className="text-sm opacity-60 mb-4">{t('settings.ai.description')}</p><div className="space-y-3"><select value={s.aiProvider} onChange={e=>s.setAIProvider(e.target.value as AIProvider)}><option value="gemini">Google Gemini</option><option value="openai">OpenAI GPT</option><option value="anthropic">Anthropic Claude</option><option value="ollama">Ollama ({t('settings.ai.local')})</option></select>{s.aiProvider!=='ollama'&&<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={t('settings.ai.apiKey')}/>}<input value={model} onChange={e=>setModel(e.target.value)} placeholder={t('settings.ai.model')}/>{s.aiProvider==='ollama'&&<input value={s.ollamaEndpoint} onChange={e=>s.setOllamaEndpoint(e.target.value)}/>}<div className="flex gap-2"><button className="btn" onClick={()=>saveAI(true)}>{t('settings.ai.test')}</button><button className="btn-primary" onClick={()=>saveAI(false)}>{t('settings.ai.save')}</button></div>{status&&<p className="text-xs opacity-70">{status}</p>}</div></Section>}
        {tab==='help'&&<Section title={t('settings.help.title')} icon={<CircleHelp/>}><div className="space-y-3">{['accounts','sync','password','ai'].map(k=><details key={k} className="p-4 rounded-xl bg-zinc-500/10"><summary className="font-semibold cursor-pointer">{t(`settings.help.${k}.q`)}</summary><p className="text-sm opacity-65 mt-2">{t(`settings.help.${k}.a`)}</p></details>)}<button className="btn-primary">{t('settings.help.askAI')}</button></div></Section>}
        {tab==='about'&&<Section title={t('settings.about.title')} icon={<Info/>}><img src="/sift-mail-icon.png" className="w-20 h-20 rounded-2xl mb-4"/><h2 className="text-2xl font-black">Sift Mail</h2><p className="opacity-60">{t('settings.about.description')}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><dt>{t('settings.about.version')}</dt><dd>0.6.0</dd><dt>{t('settings.about.engine')}</dt><dd>Multi-provider IMAP/SMTP + configurable AI</dd><dt>{t('settings.about.developer')}</dt><dd>{t('settings.about.hidden')}</dd></dl></Section>}
      </div></main></div>
  </div>;
};

const Section=({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode})=><section className="rounded-2xl bg-zinc-500/[.08] p-6"><h2 className="flex items-center gap-2 font-bold mb-5">{icon}{title}</h2>{children}</section>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="text-sm"><span className="block opacity-60 mb-2">{label}</span>{children}</label>;
const Toggle=({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void})=><label className="flex justify-between items-center"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;
