import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Bold, ChevronDown, FileUp, Italic, Link, MailPlus, Maximize2, Minimize2, Paperclip, Send, Trash2, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { ConnectedAccount, EmailMessage } from '../types';
import { DynamicSyncCredentials } from '../services/mailSyncService';
import { detectMailProvider } from '../../core/mail/providerManager';
import { safeFetchJson } from '../services/apiClient';
import { AppTheme } from '../stores/useSettingsStore';

type Attachment = { filename:string; content:string; encoding:'base64'; contentType?:string; size:number; source:'file'|'email' };
interface Props { isOpen:boolean; onClose:()=>void; accounts:ConnectedAccount[]; contacts:string[]; credentials:Record<string,DynamicSyncCredentials>; theme:AppTheme; availableEmails?:EmailMessage[]; initialForward?:EmailMessage|null; onSent:(data:{to:string;subject:string;body:string;accountId:string})=>void; }

const bytesToBase64=(bytes:Uint8Array)=>{let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)};
const textToBase64=(value:string)=>bytesToBase64(new TextEncoder().encode(value));
const safeName=(value:string)=>value.replace(/[\\/:*?"<>|]/g,'_').slice(0,80)||'email';
const emailAsEml=(email:EmailMessage)=>[`From: ${email.fromEmail||email.from}`,`To: ${(email.to||[]).join(', ')}`,`Subject: ${email.subject}`,`Date: ${email.date}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','',email.bodyText||email.snippet].join('\r\n');

export const ComposeModal:React.FC<Props>=({isOpen,onClose,accounts,contacts,credentials,theme,availableEmails=[],initialForward,onSent})=>{
  const {t}=useTranslation();
  const [accountId,setAccountId]=useState(''); const [to,setTo]=useState(''); const [cc,setCc]=useState(''); const [bcc,setBcc]=useState('');
  const [subject,setSubject]=useState(''); const [body,setBody]=useState(''); const [attachments,setAttachments]=useState<Attachment[]>([]);
  const [showCc,setShowCc]=useState(false); const [showMailPicker,setShowMailPicker]=useState(false); const [expanded,setExpanded]=useState(false);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const fileInput=useRef<HTMLInputElement>(null); const bodyRef=useRef<HTMLTextAreaElement>(null);
  const totalSize=useMemo(()=>attachments.reduce((sum,item)=>sum+item.size,0),[attachments]);

  useEffect(()=>{if(isOpen&&!accountId)setAccountId(accounts[0]?.id||'');const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[isOpen,onClose,accounts,accountId]);
  useEffect(()=>{if(!isOpen||!initialForward)return;setSubject(initialForward.subject.startsWith('Fwd:')?initialForward.subject:`Fwd: ${initialForward.subject}`);setBody(`\n\n---------- İletilen ileti ----------\nGönderen: ${initialForward.from}\nTarih: ${initialForward.date}\nKonu: ${initialForward.subject}\n\n${initialForward.bodyText||initialForward.snippet}`)},[isOpen,initialForward]);
  if(!isOpen)return null;

  const addFiles=async(files:FileList|null)=>{if(!files)return;setError('');const next:Attachment[]=[];for(const file of Array.from(files)){if(file.size>20*1024*1024){setError(`${file.name}: 20 MB sınırını aşıyor.`);continue}next.push({filename:file.name,content:bytesToBase64(new Uint8Array(await file.arrayBuffer())),encoding:'base64',contentType:file.type||'application/octet-stream',size:file.size,source:'file'})}setAttachments(prev=>[...prev,...next].slice(0,20))};
  const attachEmail=(email:EmailMessage)=>{const raw=emailAsEml(email);setAttachments(prev=>[...prev,{filename:`${safeName(email.subject)}.eml`,content:textToBase64(raw),encoding:'base64',contentType:'message/rfc822',size:new TextEncoder().encode(raw).length,source:'email'}]);setShowMailPicker(false)};
  const wrapSelection=(before:string,after=before)=>{const el=bodyRef.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;setBody(body.slice(0,start)+before+body.slice(start,end)+after+body.slice(end));setTimeout(()=>el.focus(),0)};
  const reset=()=>{setTo('');setCc('');setBcc('');setSubject('');setBody('');setAttachments([]);setError('');setShowCc(false);setShowMailPicker(false)};
  const close=()=>{reset();onClose()};
  const send=async()=>{const account=accounts.find(a=>a.id===accountId);const cred=credentials[accountId];if(!account||(!cred?.password&&!cred?.accessToken)){setError(t('compose.loginRequired'));return}if(!to.trim()||!subject.trim()||!body.trim()){setError(t('compose.required'));return}if(totalSize>25*1024*1024){setError('Eklerin toplam boyutu 25 MB sınırını aşıyor.');return}setBusy(true);setError('');try{const provider=detectMailProvider(account.email);await safeFetchJson('/api/smtp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:{host:account.imapConfig?.smtpHost||provider.smtpHost,port:account.imapConfig?.smtpPort||provider.smtpPort,secure:(account.imapConfig?.smtpPort||provider.smtpPort)===465,auth:{user:account.email,...(cred.accessToken?{accessToken:cred.accessToken}:{pass:cred.password})}},mail:{to,cc:cc||undefined,bcc:bcc||undefined,subject,text:body,attachments:attachments.map(({size,source,...item})=>item)}})});onSent({to,subject,body,accountId});reset();onClose()}catch(e:any){setError(e.message||t('compose.error'))}finally{setBusy(false)}};

  return <div className="fixed inset-0 z-50 bg-black/55 flex items-end sm:items-center justify-center sm:justify-end p-0 sm:p-5" data-testid="compose-modal"><div className={`${expanded?'w-full h-full':'w-full sm:w-[650px] sm:h-[76vh]'} theme-panel border theme-border flex flex-col shadow-2xl sm:rounded-2xl overflow-hidden`}>
    <header className="theme-elevated flex items-center justify-between px-4 py-3 border-b theme-border"><h2 className="text-sm font-semibold">{t('compose.title')}</h2><div className="flex gap-1"><button aria-label={t('compose.minimize')} className="p-1.5 theme-hover rounded"><Minimize2 size={15}/></button><button aria-label={t('compose.expand')} onClick={()=>setExpanded(!expanded)} className="p-1.5 theme-hover rounded"><Maximize2 size={15}/></button><button aria-label={t('actions.close')} onClick={close} className="p-1.5 theme-hover rounded"><X size={16}/></button></div></header>
    <div className="px-4 border-b border-zinc-500/20"><label className="flex items-center gap-3 py-2 text-sm"><span className="w-16 opacity-55">{t('compose.from')}</span><select aria-label={t('compose.from')} value={accountId} onChange={e=>setAccountId(e.target.value)} className="flex-1 bg-transparent border-0 py-1">{accounts.map(a=><option key={a.id} value={a.id}>{a.displayName} &lt;{a.email}&gt;</option>)}</select></label>
      <div className="flex items-center gap-3 py-2 border-t border-zinc-500/15"><span className="w-16 text-sm opacity-55">{t('compose.to')}</span><input autoFocus list="sift-contacts" value={to} onChange={e=>setTo(e.target.value)} placeholder="ad@example.com" className="flex-1 bg-transparent border-0 p-0"/><button onClick={()=>setShowCc(!showCc)} className="text-xs opacity-65 hover:opacity-100">Cc / Bcc</button></div><datalist id="sift-contacts">{contacts.map(x=><option key={x} value={x}/>)}</datalist>
      {showCc&&<><label className="flex items-center gap-3 py-2 border-t border-zinc-500/15"><span className="w-16 text-sm opacity-55">Cc</span><input value={cc} onChange={e=>setCc(e.target.value)} className="flex-1 bg-transparent border-0 p-0"/></label><label className="flex items-center gap-3 py-2 border-t border-zinc-500/15"><span className="w-16 text-sm opacity-55">Bcc</span><input value={bcc} onChange={e=>setBcc(e.target.value)} className="flex-1 bg-transparent border-0 p-0"/></label></>}
      <input value={subject} onChange={e=>setSubject(e.target.value)} placeholder={t('compose.subject')} className="w-full bg-transparent border-0 border-t border-zinc-500/15 px-0 py-3"/>
    </div>
    <textarea ref={bodyRef} value={body} onChange={e=>setBody(e.target.value)} placeholder={t('compose.body')} className="flex-1 resize-none bg-transparent border-0 p-4 leading-relaxed min-h-48"/>
    {attachments.length>0&&<div className="px-4 py-2 flex flex-wrap gap-2 border-t border-zinc-500/15">{attachments.map((item,index)=><span key={`${item.filename}-${index}`} className="inline-flex items-center gap-2 rounded-full bg-zinc-500/10 px-3 py-1.5 text-xs"><Paperclip size={13}/>{item.filename}<span className="opacity-50">{(item.size/1024).toFixed(0)} KB</span><button onClick={()=>setAttachments(v=>v.filter((_,i)=>i!==index))}><X size={13}/></button></span>)}</div>}
    {showMailPicker&&<div className="mx-4 mb-2 max-h-36 overflow-y-auto rounded-xl border theme-border p-2"><p className="text-xs opacity-55 px-2 py-1">{t('compose.pickEmail')}</p>{availableEmails.slice(0,50).map(email=><button key={email.id} onClick={()=>attachEmail(email)} className="w-full text-left px-2 py-2 rounded-lg theme-hover"><span className="block text-xs font-semibold truncate">{email.subject}</span><span className="block text-[11px] opacity-50 truncate">{email.from}</span></button>)}</div>}
    {error&&<p role="alert" className="px-4 pb-2 text-sm text-rose-500">{error}</p>}
    <footer className="theme-elevated flex items-center gap-1 px-4 py-3 border-t theme-border"><button disabled={busy} onClick={send} className="btn-primary flex items-center gap-2 px-5"><Send size={16}/>{busy?t('compose.sending'):t('compose.send')}<ChevronDown size={14}/></button><input ref={fileInput} type="file" multiple className="hidden" onChange={e=>void addFiles(e.target.files)}/><button title={t('compose.attachFile')} onClick={()=>fileInput.current?.click()} className="p-2.5 rounded-lg theme-hover"><FileUp size={18}/></button><button title={t('compose.attachEmail')} onClick={()=>setShowMailPicker(!showMailPicker)} className="p-2.5 rounded-lg theme-hover"><MailPlus size={18}/></button><button title={t('compose.bold')} onClick={()=>wrapSelection('**')} className="p-2.5 rounded-lg theme-hover"><Bold size={17}/></button><button title={t('compose.italic')} onClick={()=>wrapSelection('_')} className="p-2.5 rounded-lg theme-hover"><Italic size={17}/></button><button title={t('compose.link')} onClick={()=>wrapSelection('[','](https://)')} className="p-2.5 rounded-lg theme-hover"><Link size={17}/></button><span className="flex-1"/><button title={t('compose.discard')} onClick={reset} className="p-2.5 rounded-lg hover:bg-rose-500/10 text-rose-500"><Trash2 size={17}/></button></footer>
  </div></div>;
};
