import React, { useEffect, useState } from 'react';
import { CheckCircle2, CircleOff, Plug, RefreshCw, Settings2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { safeFetchJson } from '../services/apiClient';
import { AIProvider, useSettingsStore } from '../stores/useSettingsStore';

type PluginStatus='NOT_CONFIGURED'|'CONFIGURED'|'CONNECTED'|'DISABLED'|'ERROR';
type Plugin={id:string;name:string;kind:string;capabilities:string[];enabled:boolean;status:PluginStatus;message?:string};

export function IntegrationsSettings(){
 const {t}=useTranslation();const [plugins,setPlugins]=useState<Plugin[]>([]);const [open,setOpen]=useState<string|null>(null);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const settings=useSettingsStore();
 const [config,setConfig]=useState<Record<string,{apiKey:string;endpoint:string;model:string}>>({});
 const load=async()=>{try{const data=await safeFetchJson<any>('/api/plugins');setPlugins((data.plugins||[]).filter((p:Plugin)=>p.id!=='sift-local'))}catch(e:any){setMessage(e.message)}};
 useEffect(()=>{void load()},[]);
 const act=async(id:string,action:'configure'|'test'|'enable'|'disable')=>{setBusy(`${id}:${action}`);setMessage('');try{const c=config[id]||{apiKey:'',endpoint:'',model:''};const data=await safeFetchJson<any>(`/api/plugins/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:action==='configure'?JSON.stringify({apiKey:c.apiKey||undefined,endpoint:c.endpoint||undefined,model:c.model||undefined}):'{}'});if(['gemini','openai','anthropic','ollama'].includes(id)){if(action==='disable'&&settings.aiProvider===id)settings.setAIEnabled(false);if(action==='enable'){settings.setAIProvider(id as AIProvider);settings.setAIEnabled(true)}}setMessage(data.plugin?.message||t('integrations.done'));setConfig(prev=>({...prev,[id]:{...c,apiKey:''}}));await load()}catch(e:any){setMessage(e.message||t('integrations.failed'))}finally{setBusy('')}};
 return <section className="max-w-4xl mx-auto rounded-2xl bg-zinc-500/[.08] p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold text-lg">{t('integrations.title')}</h2><p className="text-sm opacity-60">{t('integrations.description')}</p></div><button className="btn" onClick={()=>void load()} aria-label={t('integrations.refresh')}><RefreshCw size={16}/></button></div>
  {message&&<p role="status" className="mb-4 text-sm rounded-xl bg-zinc-500/10 p-3">{message}</p>}
  <div className="grid md:grid-cols-2 gap-3">{plugins.map(plugin=>{const c=config[plugin.id]||{apiKey:'',endpoint:'',model:''};const isJev=plugin.id==='jev';return <article key={plugin.id} className="rounded-2xl border border-zinc-500/20 p-4" data-testid={`plugin-${plugin.id}`}><div className="flex gap-3 items-start"><div className="p-2 rounded-xl bg-zinc-500/10"><Plug size={18}/></div><div className="min-w-0 flex-1"><h3 className="font-bold">{plugin.name}</h3><p className="text-xs opacity-55">{t(`integrations.kinds.${plugin.kind}`)}</p></div><Status value={plugin.status}/></div><p className="text-xs opacity-60 mt-3">{plugin.capabilities.map(x=>t(`integrations.capabilities.${x}`)).join(' · ')}</p>{plugin.message&&<p className="text-xs text-amber-500 mt-2">{plugin.message}</p>}<div className="flex flex-wrap gap-2 mt-4"><button className="btn" onClick={()=>setOpen(open===plugin.id?null:plugin.id)}><Settings2 size={14}/>{t('integrations.configure')}</button><button className="btn" disabled={Boolean(busy)} onClick={()=>void act(plugin.id,'test')}>{t('integrations.test')}</button>{plugin.enabled?<button className="btn" disabled={Boolean(busy)} onClick={()=>void act(plugin.id,'disable')}><CircleOff size={14}/>{t('integrations.disable')}</button>:<button className="btn-primary" disabled={Boolean(busy)||isJev} onClick={()=>void act(plugin.id,'enable')}><CheckCircle2 size={14}/>{t('integrations.enable')}</button>}</div>{open===plugin.id&&<div className="space-y-2 mt-4 pt-4 border-t border-zinc-500/20">{plugin.id!=='ollama'&&<input type="password" value={c.apiKey} onChange={e=>setConfig(v=>({...v,[plugin.id]:{...c,apiKey:e.target.value}}))} placeholder={t('integrations.apiKey')} autoComplete="new-password"/>}<input value={c.endpoint} onChange={e=>setConfig(v=>({...v,[plugin.id]:{...c,endpoint:e.target.value}}))} placeholder={t('integrations.endpoint')}/>{!isJev&&<input value={c.model} onChange={e=>setConfig(v=>({...v,[plugin.id]:{...c,model:e.target.value}}))} placeholder={t('integrations.model')}/>}<button className="btn-primary" disabled={Boolean(busy)} onClick={()=>void act(plugin.id,'configure')}>{t('integrations.save')}</button></div>}</article>})}</div><p className="text-xs opacity-55 mt-5">{t('integrations.localFallback')}</p></section>;
}
const Status=({value}:{value:PluginStatus})=>{const {t}=useTranslation();const color=value==='CONNECTED'?'text-emerald-500':value==='ERROR'?'text-rose-500':'text-amber-500';return <span className={`text-[10px] font-bold ${color}`}>{t(`integrations.status.${value}`)}</span>};
